// kobPlay/web/src/components/BaseView.vue
<template>
    <div class="container">
        <div class="card">
            <div class="card-body">
                <slot></slot>
            </div>
        </div>
    </div>

</template>



<script>


export default {
    name: "BaseView",

}
</script>



<style scoped>
.container {
    margin-top: 30px;
}


</style>

// webcalculator/src/component/content/baseView.jsx
import React, { Component } from 'react'

class BaseView extends Component {
    state = {}
    render() {
        return (
                <div className="container" style={{ marginTop: "20px" }}>
                    <div className="card">
                        <div className="card-body">
                            {this.props.children}
                        </div>
                    </div>
                </div>
        );
    }
}

export default BaseView;
